/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as ApiCompileRouteImport } from './routes/api/compile'
import { Route as LayoutDashIndexRouteImport } from './routes/_layout.dash.index'
import { Route as LayoutDashKeysRouteImport } from './routes/_layout.dash.keys'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiCompileRoute = ApiCompileRouteImport.update({
  id: '/api/compile',
  path: '/api/compile',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutDashIndexRoute = LayoutDashIndexRouteImport.update({
  id: '/dash/',
  path: '/dash/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashKeysRoute = LayoutDashKeysRouteImport.update({
  id: '/dash/keys',
  path: '/dash/keys',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/api/compile': typeof ApiCompileRoute
  '/dash/keys': typeof LayoutDashKeysRoute
  '/dash/': typeof LayoutDashIndexRoute
}
export interface FileRoutesByTo {
  '/api/compile': typeof ApiCompileRoute
  '/': typeof LayoutIndexRoute
  '/dash/keys': typeof LayoutDashKeysRoute
  '/dash': typeof LayoutDashIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/api/compile': typeof ApiCompileRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/dash/keys': typeof LayoutDashKeysRoute
  '/_layout/dash/': typeof LayoutDashIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/compile' | '/dash/keys' | '/dash/'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/compile' | '/' | '/dash/keys' | '/dash'
  id:
    | '__root__'
    | '/_layout'
    | '/api/compile'
    | '/_layout/'
    | '/_layout/dash/keys'
    | '/_layout/dash/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ApiCompileRoute: typeof ApiCompileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/compile': {
      id: '/api/compile'
      path: '/api/compile'
      fullPath: '/api/compile'
      preLoaderRoute: typeof ApiCompileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/dash/': {
      id: '/_layout/dash/'
      path: '/dash'
      fullPath: '/dash/'
      preLoaderRoute: typeof LayoutDashIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dash/keys': {
      id: '/_layout/dash/keys'
      path: '/dash/keys'
      fullPath: '/dash/keys'
      preLoaderRoute: typeof LayoutDashKeysRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutDashKeysRoute: typeof LayoutDashKeysRoute
  LayoutDashIndexRoute: typeof LayoutDashIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutDashKeysRoute: LayoutDashKeysRoute,
  LayoutDashIndexRoute: LayoutDashIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ApiCompileRoute: ApiCompileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
