/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiCompileRouteImport } from './routes/api/compile'
import { Route as LayoutDashIndexRouteImport } from './routes/_layout.dash.index'
import { Route as LlmsDotmdxDocsSplatRouteImport } from './routes/llms[.]mdx.docs.$'
import { Route as LayoutDashKeysRouteImport } from './routes/_layout.dash.keys'

const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompileRoute = ApiCompileRouteImport.update({
  id: '/api/compile',
  path: '/api/compile',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutDashIndexRoute = LayoutDashIndexRouteImport.update({
  id: '/dash/',
  path: '/dash/',
  getParentRoute: () => LayoutRoute,
} as any)
const LlmsDotmdxDocsSplatRoute = LlmsDotmdxDocsSplatRouteImport.update({
  id: '/llms.mdx/docs/$',
  path: '/llms.mdx/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutDashKeysRoute = LayoutDashKeysRouteImport.update({
  id: '/dash/keys',
  path: '/dash/keys',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/compile': typeof ApiCompileRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/dash/keys': typeof LayoutDashKeysRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/dash/': typeof LayoutDashIndexRoute
}
export interface FileRoutesByTo {
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/compile': typeof ApiCompileRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/': typeof LayoutIndexRoute
  '/dash/keys': typeof LayoutDashKeysRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/dash': typeof LayoutDashIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/compile': typeof ApiCompileRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/dash/keys': typeof LayoutDashKeysRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/_layout/dash/': typeof LayoutDashIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/compile'
    | '/api/search'
    | '/docs/$'
    | '/dash/keys'
    | '/llms.mdx/docs/$'
    | '/dash/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/compile'
    | '/api/search'
    | '/docs/$'
    | '/'
    | '/dash/keys'
    | '/llms.mdx/docs/$'
    | '/dash'
  id:
    | '__root__'
    | '/_layout'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/compile'
    | '/api/search'
    | '/docs/$'
    | '/_layout/'
    | '/_layout/dash/keys'
    | '/llms.mdx/docs/$'
    | '/_layout/dash/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ApiCompileRoute: typeof ApiCompileRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  LlmsDotmdxDocsSplatRoute: typeof LlmsDotmdxDocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compile': {
      id: '/api/compile'
      path: '/api/compile'
      fullPath: '/api/compile'
      preLoaderRoute: typeof ApiCompileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/dash/': {
      id: '/_layout/dash/'
      path: '/dash'
      fullPath: '/dash/'
      preLoaderRoute: typeof LayoutDashIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/llms.mdx/docs/$': {
      id: '/llms.mdx/docs/$'
      path: '/llms.mdx/docs/$'
      fullPath: '/llms.mdx/docs/$'
      preLoaderRoute: typeof LlmsDotmdxDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/dash/keys': {
      id: '/_layout/dash/keys'
      path: '/dash/keys'
      fullPath: '/dash/keys'
      preLoaderRoute: typeof LayoutDashKeysRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutDashKeysRoute: typeof LayoutDashKeysRoute
  LayoutDashIndexRoute: typeof LayoutDashIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutDashKeysRoute: LayoutDashKeysRoute,
  LayoutDashIndexRoute: LayoutDashIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ApiCompileRoute: ApiCompileRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  LlmsDotmdxDocsSplatRoute: LlmsDotmdxDocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
