// ============================================================
// GENERATED Rust: Orderbook Program
// Source: orderbook-program.ts
// Generated by @better-sol/cli transpiler
//
// This is what the transpiler produces from the TypeScript
// orderbook definition. Zero-copy accounts use AccountLoader
// instead of Account, and boolean flags are explicit u8 fields.
// ============================================================

use anchor_lang::prelude::*;
use anchor_lang::solana_program::msg;
use anchor_spl::token::{self, Token, Mint, TokenAccount, Transfer, MintTo, Burn};

declare_id!("0rdrB00k11111111111111111111111111111111111");

// ══════════════════════════════════════════
// ZERO-COPY TYPES
// ══════════════════════════════════════════

#[zero_copy]
#[derive(Debug)]
pub struct Order {
    pub trader: Pubkey,       // 32 bytes
    pub price: u64,           // 8 bytes
    pub quantity: u64,        // 8 bytes
    pub side: u8,             // 1 byte
    pub timestamp: i64,       // 8 bytes
    // Total: 57 bytes + 7 padding = 64 bytes (u64 alignment)
}

#[zero_copy]
#[derive(Debug)]
pub struct MarketInfo {
    pub base_decimals: u8,
    pub quote_decimals: u8,
    pub min_order_size: u64,  // +6 padding for u64 alignment
    pub tick_size: u64,
}

// ══════════════════════════════════════════
// ACCOUNTS
// ══════════════════════════════════════════

#[account(zero_copy)]
pub struct OrderBook {
    pub market: Pubkey,              // 32
    pub base_mint: Pubkey,           // 32
    pub quote_mint: Pubkey,          // 32
    pub market_info: MarketInfo,     // 24
    pub bid_count: u32,              // 4
    pub ask_count: u32,              // 4
    pub best_bid: u64,               // 8
    pub best_ask: u64,               // 8
    pub total_bid_volume: u64,       // 8
    pub total_ask_volume: u64,       // 8
    pub is_active: u8,
    pub bump: u8,                    // 1
    // +6 padding for array alignment
    pub bids: [Order; 256],          // 64 * 256 = 16384
    pub asks: [Order; 256],          // 64 * 256 = 16384
}
// Space: 8 (discriminator) + 32 + 32 + 32 + 24 + 4 + 4 + 8 + 8 + 8 + 8 + 1 + 1 + 6 + 16384 + 16384 = 32,964

#[account]
pub struct FillRecord {
    pub order_book: Pubkey,
    pub trader: Pubkey,
    pub is_bid: bool,
    pub price: u64,
    pub quantity: u64,
    pub timestamp: i64,
}
// Space: 8 + 32 + 32 + 1 + 7 + 8 + 8 + 8 = 104

#[account]
pub struct TradeHistory {
    pub order_book: Pubkey,
    pub trade_count: u64,
    pub total_volume: u64,
    pub high_price: u64,
    pub low_price: u64,
    pub last_price: u64,
}
// Space: 8 + 32 + 8 + 8 + 8 + 8 + 8 = 80


// ══════════════════════════════════════════
// ERROR CODES
// ══════════════════════════════════════════

#[error_code]
pub enum ErrorCode {
    #[msg("Not authorized to perform this action")]
    Unauthorized,
    #[msg("Orderbook is not active")]
    OrderbookInactive,
    #[msg("No space for more orders on this side")]
    OrderbookFull,
    #[msg("Price must be greater than zero")]
    InvalidPrice,
    #[msg("Quantity must be greater than zero")]
    InvalidQuantity,
    #[msg("Side must be 0 (bid) or 1 (ask)")]
    InvalidSide,
    #[msg("No orders to match")]
    NoOrders,
    #[msg("Cannot match own orders")]
    SelfTrade,
    #[msg("Price below minimum order size")]
    PriceBelowMin,
    #[msg("No matching orders found")]
    NoMatchFound,
}


// ══════════════════════════════════════════
// EVENTS
// ══════════════════════════════════════════

#[event]
pub struct OrderPlaced {
    pub trader: Pubkey,
    pub side: u8,
    pub price: u64,
    pub quantity: u64,
    pub order_index: u32,
}

#[event]
pub struct OrdersMatched {
    pub match_count: u32,
    pub total_quantity: u64,
}

#[event]
pub struct OrderbookClosed {
    pub market: Pubkey,
}

#[event]
pub struct PriceUpdated {
    pub best_bid: u64,
    pub best_ask: u64,
}


// ══════════════════════════════════════════
// PROGRAM INSTRUCTIONS
// ══════════════════════════════════════════

#[program]
pub mod orderbook {
    use super::*;

    // ── 1. Initialize ──
    pub fn initialize(
        ctx: Context<Initialize>,
        base_mint: Pubkey,
        quote_mint: Pubkey,
        base_decimals: u8,
        quote_decimals: u8,
        min_order_size: u64,
        tick_size: u64,
    ) -> Result<()> {
        let book = &mut ctx.accounts.book.load_init()?;
        book.market = ctx.accounts.admin.key();
        book.base_mint = base_mint;
        book.quote_mint = quote_mint;
        book.market_info = MarketInfo { base_decimals, quote_decimals, min_order_size, tick_size };
        book.bid_count = 0;
        book.ask_count = 0;
        book.best_bid = 0;
        book.best_ask = 0;
        book.total_bid_volume = 0;
        book.total_ask_volume = 0;
        book.is_active = 1u8;
        Ok(())
    }

    // ── 2. Place Bid ──
    pub fn place_bid(
        ctx: Context<PlaceBid>,
        price: u64,
        quantity: u64,
    ) -> Result<()> {
        {
            let book = &mut ctx.accounts.book.load_mut()?;
            require!(book.is_active != 0, ErrorCode::OrderbookInactive);
            require!(price > 0, ErrorCode::InvalidPrice);
            require!(price >= book.market_info.min_order_size, ErrorCode::PriceBelowMin);
            require!(quantity > 0, ErrorCode::InvalidQuantity);
            require!(book.bid_count < 256, ErrorCode::OrderbookFull);

            book.bids[book.bid_count as usize] = Order {
                trader: ctx.accounts.trader.key(),
                price,
                quantity,
                side: 0,
                timestamp: Clock::get()?.unix_timestamp,
            };

            book.bid_count += 1;
            book.total_bid_volume += quantity;

            if price > book.best_bid {
                book.best_bid = price;
            }
        } // ← borrow dropped before emit

        emit!(OrderPlaced {
            trader: ctx.accounts.trader.key(),
            side: 0,
            price,
            quantity,
            // order_index omitted for simplicity
        });

        Ok(())
    }

    // ── 3. Place Ask ──
    pub fn place_ask(
        ctx: Context<PlaceAsk>,
        price: u64,
        quantity: u64,
    ) -> Result<()> {
        {
            let book = &mut ctx.accounts.book.load_mut()?;
            require!(book.is_active != 0, ErrorCode::OrderbookInactive);
            require!(price > 0, ErrorCode::InvalidPrice);
            require!(quantity > 0, ErrorCode::InvalidQuantity);
            require!(book.ask_count < 256, ErrorCode::OrderbookFull);

            book.asks[book.ask_count as usize] = Order {
                trader: ctx.accounts.trader.key(),
                price,
                quantity,
                side: 1,
                timestamp: Clock::get()?.unix_timestamp,
            };

            book.ask_count += 1;
            book.total_ask_volume += quantity;

            if book.best_ask == 0 || price < book.best_ask {
                book.best_ask = price;
            }
        }

        emit!(OrderPlaced {
            trader: ctx.accounts.trader.key(),
            side: 1,
            price,
            quantity,
        });

        Ok(())
    }

    // ── 4. Match Orders ──
    //
    // Uses ctx.remaining_accounts for dynamic fill records.
    // The TypeScript p.remaining(FillRecord) generates:
    // - No field in the Accounts struct
    // - Typed deserialization via Account::<FillRecord>::try_from()
    //
    pub fn match_orders(
        ctx: Context<MatchOrders>,
        max_matches: u32,
    ) -> Result<()> {
        {
            let book = &mut ctx.accounts.book.load_mut()?;
            require!(book.is_active != 0, ErrorCode::OrderbookInactive);
            require!(book.bid_count > 0, ErrorCode::NoOrders);
            require!(book.ask_count > 0, ErrorCode::NoOrders);

            let limit = std::cmp::min(ctx.remaining_accounts.len(), max_matches as usize);

            let mut match_count: u32 = 0;
            let mut total_quantity: u64 = 0;

            for i in 0..limit {
                let bid = &book.bids[i];
                let ask = &book.asks[i];

                if bid.quantity == 0 || ask.quantity == 0 {
                    continue;
                }

                if bid.trader == ask.trader {
                    continue;
                }

                if bid.price >= ask.price {
                    let match_qty = std::cmp::min(bid.quantity, ask.quantity);
                    let match_price = bid.price;

                    // Write fill record (remaining account)
                    let fill_ai = &ctx.remaining_accounts[i];
                    let mut fill = Account::<FillRecord>::try_from(fill_ai)?;
                    fill.order_book = ctx.accounts.book.key();
                    fill.trader = bid.trader;
                    fill.is_bid = true;
                    fill.price = match_price;
                    fill.quantity = match_qty;
                    fill.timestamp = Clock::get()?.unix_timestamp;

                    // Update zero-copy array
                    // NOTE: We already have a mutable borrow on book,
                    // so we access bids/asks mutably directly
                    book.bids[i].quantity -= match_qty;
                    book.asks[i].quantity -= match_qty;

                    match_count += 1;
                    total_quantity += match_qty;
                }
            }

            require!(match_count > 0, ErrorCode::NoMatchFound);

            // Update trade history
            ctx.accounts.history.trade_count += match_count as u64;
            ctx.accounts.history.total_volume += total_quantity;
            ctx.accounts.history.last_price = book.best_bid;
        }

        emit!(OrdersMatched {
            match_count: 0, // simplified
            total_quantity: 0,
        });

        msg!("Matched orders");

        Ok(())
    }

    // ── 5. Cancel Order ──
    pub fn cancel_order(
        ctx: Context<CancelOrder>,
        order_index: u32,
        side: u8,
    ) -> Result<()> {
        let book = &mut ctx.accounts.book.load_mut()?;
        require!(book.is_active != 0, ErrorCode::OrderbookInactive);
        require!(side == 0 || side == 1, ErrorCode::InvalidSide);

        let count = if side == 0 { book.bid_count } else { book.ask_count };
        require!(order_index < count, ErrorCode::InvalidPrice);

        let idx = order_index as usize;
        let orders = if side == 0 { &mut book.bids[..] } else { &mut book.asks[..] };

        require!(orders[idx].trader == ctx.accounts.trader.key(), ErrorCode::Unauthorized);

        let qty = orders[idx].quantity;
        orders[idx] = Order {
            trader: Pubkey::default(),
            price: 0,
            quantity: 0,
            side: 0,
            timestamp: 0,
        };

        if side == 0 {
            book.total_bid_volume -= qty;
        } else {
            book.total_ask_volume -= qty;
        }

        Ok(())
    }

    // ── 6. Close ──
    pub fn close(ctx: Context<CloseBook>) -> Result<()> {
        let book = &mut ctx.accounts.book.load_mut()?;
        require!(ctx.accounts.admin.key() == book.market, ErrorCode::Unauthorized);
        book.is_active = 0u8;

        emit!(OrderbookClosed {
            market: book.market,
        });

        Ok(())
    }
}


// ══════════════════════════════════════════
// ACCOUNT VALIDATION STRUCTS
// ══════════════════════════════════════════

#[derive(Accounts)]
pub struct Initialize<'info> {
    #[account(
        init,
        payer = admin,
        space = 32964,  // 8 + std::mem::size_of::<OrderBook>()
        seeds = [b"orderbook", admin.key().as_ref()],
        bump,
    )]
    pub book: AccountLoader<'info, OrderBook>,
    #[account(mut)]
    pub admin: Signer<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct PlaceBid<'info> {
    #[account(
        mut,
        seeds = [b"orderbook", book.load()?.market.as_ref()],
        bump,
    )]
    pub book: AccountLoader<'info, OrderBook>,
    #[account(mut)]
    pub trader: Signer<'info>,
}

#[derive(Accounts)]
pub struct PlaceAsk<'info> {
    #[account(
        mut,
        seeds = [b"orderbook", book.load()?.market.as_ref()],
        bump,
    )]
    pub book: AccountLoader<'info, OrderBook>,
    #[account(mut)]
    pub trader: Signer<'info>,
}

#[derive(Accounts)]
pub struct MatchOrders<'info> {
    #[account(
        mut,
        seeds = [b"orderbook", book.load()?.market.as_ref()],
        bump,
    )]
    pub book: AccountLoader<'info, OrderBook>,
    #[account(mut)]
    pub base_reserve: Account<'info, TokenAccount>,
    #[account(mut)]
    pub quote_reserve: Account<'info, TokenAccount>,
    #[account(mut)]
    pub matching_engine: Signer<'info>,
    #[account(
        mut,
        seeds = [b"history", book.load()?.market.as_ref()],
        bump,
    )]
    pub history: Account<'info, TradeHistory>,
    pub token_program: Program<'info, Token>,
    // fills: NOT in the struct — uses ctx.remaining_accounts
}

#[derive(Accounts)]
pub struct CancelOrder<'info> {
    #[account(
        mut,
        seeds = [b"orderbook", book.load()?.market.as_ref()],
        bump,
    )]
    pub book: AccountLoader<'info, OrderBook>,
    #[account(mut)]
    pub trader: Signer<'info>,
}

#[derive(Accounts)]
pub struct CloseBook<'info> {
    #[account(
        mut,
        seeds = [b"orderbook", book.load()?.market.as_ref()],
        bump,
    )]
    pub book: AccountLoader<'info, OrderBook>,
    #[account(mut)]
    pub admin: Signer<'info>,
}
