import { CodeWriter } from "#generator/code-writer";
import { toCamel, toPascal } from "#lib/naming";
import type { Idl, IdlField, IdlInstructionAccount, IdlInstructionAccountItem, IdlType, IdlTypeDef, IdlTypeDefTyStruct } from "@coral-xyz/anchor/dist/esm/idl";

function flattenAccountItems(items: readonly IdlInstructionAccountItem[] | undefined): readonly IdlInstructionAccount[] {
  if (items === undefined) return [];
  const result: IdlInstructionAccount[] = [];
  for (const item of items) {
    if ("accounts" in item) result.push(...item.accounts);
    else result.push(item);
  }
  return result;
}

function idlTypeToCode(type: IdlType): string {
  if (typeof type === "string") return `bs.${type}()`;
  if ("option" in type && type.option !== undefined) return `bs.optional(${idlTypeToCode(type.option)})`;
  if ("coption" in type && type.coption !== undefined) return `bs.optional(${idlTypeToCode(type.coption)})`;
  if ("vec" in type && type.vec !== undefined) return `bs.vector(${idlTypeToCode(type.vec)})`;
  if ("array" in type && type.array !== undefined) return `bs.array(${idlTypeToCode(type.array[0])}, ${type.array[1]})`;
  if ("defined" in type) return "bs.pubkey()";
  return "bs.pubkey()";
}

function escapeString(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

type StructTypeDef = {
  readonly name: string;
  readonly type: IdlTypeDefTyStruct;
};

function isStructType(t: IdlTypeDef): t is StructTypeDef {
  return t.type.kind === "struct";
}

function getStructFields(typeDef: IdlTypeDef | undefined): readonly IdlField[] {
  if (typeDef === undefined || !isStructType(typeDef)) return [];
  const fields = typeDef.type.fields;
  if (fields === undefined) return [];
  if (!Array.isArray(fields)) return [];
  return fields as readonly IdlField[];
}

export function generateIdlProgram(idl: Idl, sourceLabel: string): string {
  const w = new CodeWriter();
  const programName = toCamel(idl.metadata.name);
  const programAddress = idl.address;
  const typesByName = new Map<string, IdlTypeDef>();
  for (const t of idl.types ?? []) typesByName.set(t.name, t);

  const accountDefs = idl.accounts ?? [];
  const resolvedAccounts = new Map<string, { readonly exportName: string; readonly fields: readonly IdlField[] }>();
  for (const acc of accountDefs) {
    const fields = getStructFields(typesByName.get(acc.name));
    resolvedAccounts.set(acc.name, { exportName: toPascal(acc.name), fields });
  }

  const eventTypes = new Set<string>();
  for (const ev of idl.events ?? []) {
    const fields = getStructFields(typesByName.get(ev.name));
    if (fields.length > 0) eventTypes.add(ev.name);
  }

  w.line(`// Generated by better-sol from ${sourceLabel}. Do not edit.`);
  w.line(`import { bs } from "better-sol/program"`);
  w.blank();

  for (const [, { exportName, fields }] of resolvedAccounts) {
    if (fields.length === 0) continue;
    w.line(`const ${exportName} = bs.account({`);
    w.indent(1);
    for (const field of fields) {
      w.line(`${toCamel(field.name)}: ${idlTypeToCode(field.type)},`);
    }
    w.indent(0);
    w.line("})");
    w.blank();
  }

  const errorEntries = idl.errors ?? [];
  const eventEntries = (idl.events ?? []).filter(e => eventTypes.has(e.name));

  w.line(`export const ${programName} = bs.program({`);
  w.indent(1);
  w.line(`name: "${escapeString(programName)}",`);
  w.line(`address: "${escapeString(programAddress)}",`);

  if (resolvedAccounts.size > 0) {
    w.line(`accounts: {`);
    for (const [, { exportName, fields }] of resolvedAccounts) {
      if (fields.length === 0) continue;
      w.line(`  ${exportName},`);
    }
    w.line(`},`);
  }

  if (errorEntries.length > 0) {
    w.line(`errors: {`);
    for (const err of errorEntries) {
      const msg = err.msg ?? err.name;
      w.line(`  ${toPascal(err.name)}: "${escapeString(msg)}",`);
    }
    w.line(`},`);
  }

  if (eventEntries.length > 0) {
    w.line(`events: {`);
    for (const ev of eventEntries) {
      const fields = getStructFields(typesByName.get(ev.name));
      w.line(`  ${toPascal(ev.name)}: {`);
      for (const f of fields) {
        w.line(`    ${toCamel(f.name)}: ${idlTypeToCode(f.type)},`);
      }
      w.line(`  },`);
    }
    w.line(`},`);
  }

  w.indent(0);
  w.line(`}, ix => ({`);

  for (const instr of idl.instructions) {
    const flatAccounts = flattenAccountItems(instr.accounts);
    const ixName = toCamel(instr.name);

    w.blank();
    w.line(`${ixName}: ix({`);

    if (flatAccounts.length > 0) {
      w.line(`  accounts: {`);
      for (const acc of flatAccounts) {
        if (acc.optional === true) continue;
        const constraint = accountToConstraint(acc, resolvedAccounts);
        w.line(`    ${toCamel(acc.name)}: ${constraint},`);
      }
      w.line(`  },`);
    }

    const args = instr.args ?? [];
    if (args.length > 0) {
      w.line(`  args: {`);
      for (const arg of args) {
        w.line(`    ${toCamel(arg.name)}: ${idlTypeToCode(arg.type)},`);
      }
      w.line(`  },`);
    }

    if (instr.returns !== undefined) {
      w.line(`  returns: ${idlTypeToCode(instr.returns)},`);
    }

    w.line(`  run: (${runParams(flatAccounts, args)}) => {`);
    w.line(`    // Implement on-chain logic`);
    w.line(`  },`);
    w.line(`}),`);
  }

  w.blank();
  w.line(`}))`);
  w.blank();

  return w.lines.join("\n");
}

function accountToConstraint(acc: IdlInstructionAccount, resolvedAccounts: Map<string, { readonly exportName: string; readonly fields: readonly IdlField[] }>): string {
  if (acc.signer === true) return "bs.signer()";

  const resolved = resolveAccountDefinition(acc.name, resolvedAccounts);
  const accountRef = resolved !== undefined && resolved.fields.length > 0 ? resolved.exportName : "bs.account({})";

  if (acc.writable === true) return `bs.mut(${accountRef})`;
  return accountRef;
}

function resolveAccountDefinition(
  accountName: string,
  resolvedAccounts: Map<string, { readonly exportName: string; readonly fields: readonly IdlField[] }>,
): { readonly exportName: string; readonly fields: readonly IdlField[] } | undefined {
  const exact = resolvedAccounts.get(accountName);
  if (exact !== undefined) return exact;

  const pascalName = toPascal(accountName);
  for (const [idlName, account] of resolvedAccounts) {
    if (idlName === pascalName || account.exportName === pascalName) return account;
  }

  return undefined;
}

function runParams(accounts: readonly IdlInstructionAccount[], args: readonly IdlField[]): string {
  const parts: string[] = [];
  const accountNames = accounts.filter(a => a.optional !== true).map(a => toCamel(a.name));
  if (accountNames.length > 0) parts.push(`{ ${accountNames.join(", ")} }`);
  const argNames = args.map(a => toCamel(a.name));
  if (argNames.length > 0) parts.push(`{ ${argNames.join(", ")} }`);
  parts.push("ctx");
  return parts.join(", ");
}
